plot(data1$newtime, data1$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(data1$newtime, data1$Sub_metering_2, col = "red")
lines(data1$newtime, data1$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), c("Sub_metering_1  ", "Sub_metering_2  ", "Sub_metering_3  "), lty = c(1, 1), lwd = c(1, 1))
dev.copy(png, "plot3.jpg", width = 480, heigh = 480)
dev.off()
